# Generated by Django 6.1 on 2026-10-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_baseline_user_githuburl_user_isemailverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='githubAccessToken',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
