# Generated by Django 5.0.8 on 2026-10-08 04:32

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FusionScoreCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_a', models.CharField(max_length=100)),
                ('skill_b', models.CharField(max_length=100)),
                ('score_json', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('skill_a', 'skill_b')},
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(default='adzuna', max_length=30)),
                ('query', models.CharField(db_index=True, default='', max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['query'], name='scores_jobl_query_98641f_idx')],
            },
        ),
    ]
