# Generated by Django 6.1 on 2026-09-08 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthLogEntry',
            fields=[
                ('entryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('github', 'GitHub')], default='manual', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sourceUrl', models.URLField(blank=True, default='')),
                ('skillTags', models.JSONField(blank=True, default=list)),
                ('competencyTags', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(default=False)),
                ('loggedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-loggedAt'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credentialId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('verificationUrl', models.URLField()),
                ('verificationStatus', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('requestedAt', models.DateTimeField(auto_now_add=True)),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='growthlog.growthlogentry')),
            ],
        ),
    ]
