# Generated by Django 6.1 on 2026-10-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthlogentry',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
