name: Backend CI Pipeline

on:
    push:
        paths:
            - 'backend/**'
            - '.github/workflows/backend-ci-pipeline.yml'

defaults:
    run:
        working-directory: backend

jobs: 
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Django
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"
            - name: Install ruff
              run: pip install ruff

            - name: Lint and write report
              run: ruff check . --output-format json --output-file ruff-report.json
              continue-on-error: true

            - name: Show lint results
              run: ruff check .

            - name: Upload lint report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: lint-report
                path: backend/ruff-report.json
                if-no-files-found: warn
                retention-days: 14
    test:
        runs-on: ubuntu-latest
        
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: SkillFusion_Database
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5431:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 10
                

        env:
            SECRET_KEY: ci-only-not-secret
            DEBUG: "True"
            DB_NAME: SkillFusion_Database
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_HOST: locahost
            DB_PORT: 5431

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with: 
                python-version: "3.13"
                cache: pip
                cache-dependency-path: backend/requirements.txt

            - name: Install dependencies
              run: |
                 pip install -r requirements.txt
                 pip install coverage
            
            - name: Django system check
              run: python manage.py check

            - name: Check for missing migrations
              run: python manage.py makemigrations --check --dry-run

            - name: Run tests with coverage
              run: |
                coverate run manage.py test
                coverage report
                coverage html -d coverage-html
            
            - name: Upload coverage report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: backend/coverage-html/
                if-no-files-found: warn
                retention-days: 14