name: CI pipeline frontend
on: 
    push:
        paths:
            - 'frontend/**'
            - '.github/workflow/frontend.yml'

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "22"
            - name: Install lint tooling
              run: npm install --no-save eslint
            - name: Lint and write report
              run: npx eslint src -f html -o lint-report.html
              continue-on-error: true
            - name: Upload lint report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: lint-report
                path: frontend/lint-report.html
                retention-days: 1
            
            